### ISSUE TITLE
out-of-bounds display still present, and a request

### ISSUE THREAD

**Issue by davephillips** [alexey-komarov/fruitsofkarma-vcvrack#3]
The graphics display is still spilling over. I'm running Rack 2.1.0 on a Mac Mini M1.

Also, can you make the display compatible with the room light dimmer ? Would be very cool. :)

Best regards,

Dave Phillips

**Comment by alexey-komarov** [comment]
Thank you, @davephillips.
 
Unfortunately I don't have Mac, only Linux + a vm with a Windows.
On both systems it works without any issues on Rack2, so there might be an issue with nvgScissors call in nanovg library on Mac. 

The issue appears only with enabled Stroke, I made some adjustments and added nvgMiterLimit call, now it doesn't go out without using scissors.

Could you please try to build rc branch: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/tree/rc

Also, I wonder does nvgScissors works on Mac. Can you try to change arguments here https://github.com/alexey-komarov/fruitsofkarma-vcvrack/blob/main/src/ColoredGlass.cpp#L240 for example 100, 100, 150, 150 and check how it looks on your Mac.

**Comment by SteveRussell33** [comment]
> Also, can you make the display compatible with the room light dimmer ? Would be very cool. :)

@davephillips I got your back!  ;) https://github.com/alexey-komarov/fruitsofkarma-vcvrack/pull/4/commits/0d794b56863061581318dd61a73976e700d2ebcb

**Comment by SteveRussell33** [comment]
Out of bounds on bottom and right hand edges. ``rc`` branch build on Windows.

![image](https://user-images.githubusercontent.com/41975381/167244071-10e2652f-c0a4-4ca1-b5a1-cdacb35c9918.png)

**Comment by alexey-komarov** [comment]
@SteveRussell33 thank your for you help and interest again, I was able to reproduce it on my windows, so will fix it soon.
Also I have to say I'm really surprised, I started this plugin due to bad weather on a weekend just for fun, pushed it to github and immediately have got lot's of feedback. Never seen such thing before in my life :)

**Comment by SteveRussell33** [comment]
You're welcome Alexey, glad to help.

The VCV Rack community just *loves* a new plugin! Welcome aboard.
If you're interested at a later date you can drop a post in the forum https://community.vcvrack.com/c/announcements/9 to get the word around to more testers/users. Also ask for some panel designs if you want.

**Comment by davephillips** [comment]
@alexey-komarov and @SteveRussell33 - Thanks, guys ! I'll rebuild the plugin this morning and report back after some tests.

Yes, there are a few of us who are "hub crawlers", we often find and build plugins that are just getting started or have little exposure. Glad to help in any way I can, I'm not a coder myself but I do know how to run a debugger in multithreaded mode. :)

**Comment by davephillips** [comment]
Rebuilt and tested (Colored Glass only, btw). The display seems fine now but there's a "racing"effect around the border. I'll make a short video to show what's happening. Dark mode works perfectly, very nice to see (thanks Steve !). 

@alexey-komarov - Do you still want me to run those test on nvgScissors ?

**Comment by SteveRussell33** [comment]
> The display seems fine now but there's a "racing"effect around the border. 

I've noticed that with one of my presets (linked), whereas others don't have that effect.
[ColoredGlass 04.zip](https://github.com/alexey-komarov/fruitsofkarma-vcvrack/files/8645112/ColoredGlass.04.zip)

**Comment by alexey-komarov** [comment]
@davephillips @SteveRussell33 
I tried to to fix it with a black frame, the stroke works definitely different on windows. I tried to draw the border using rectangles and seems I saw an effect which  can call "Racing effect". So,  I had to chang the algorithm to be not drawing those polygons which goes out of limits. Now it looks almost the same on windows and linux, could you please try? 
P.S. No need to test nvgScissors, my new approach seems works much better.

**Comment by SteveRussell33** [comment]
Still getting the "racing" effect with the preset I linked above (I would say now more noticeable) as well as with default settings on adding the module to an empty rack.

**Comment by davephillips** [comment]
https://youtu.be/vyMf66HlY-0

Shows the border racing effect.

**Comment by davephillips** [comment]
Btw:

```
% make dist -j4
c++  -std=c++11 -stdlib=libc++   -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=x86-64 -funsafe-math-optimizations -fno-omit-frame-pointer -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.9  -c -o build/src/ColoredGlass.cpp.o src/ColoredGlass.cpp
src/ColoredGlass.cpp:232:10: error: variable-sized object may not be initialized
                int xs[edges] = {};
                       ^~~~~
src/ColoredGlass.cpp:233:10: error: variable-sized object may not be initialized
                int ys[edges] = {};
                       ^~~~~
2 errors generated.
make: *** [build/src/ColoredGlass.cpp.o] Error 1
```

Pulled from rc branch:

```
From https://github.com/alexey-komarov/fruitsofkarma-vcvrack
   340e35b..87ac278  rc         -> origin/rc
Updating 340e35b..87ac278
```

**Comment by alexey-komarov** [comment]
@davephillips 
Thanks, this error is specific to your c compiler, hopefully fixed with the latest commit.
Also, I couldn't watch your video, it says it's private.

**Comment by davephillips** [comment]
@alexey-komarov - Video permissions fixed now, sorry about that. I rebuilt, the edge error is still present.

**Comment by SteveRussell33** [comment]
Effect still present using preset linked here: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/issues/3#issuecomment-1120200312 after rebuild with 290f6e3

**Comment by alexey-komarov** [comment]
@SteveRussell33, @davephillips I have refactored the algorithm, now it's more straightforward and much more accurate determine when a particle should go in backward direction, but some interesting side effects are lost. Now seems it works without difference on Linux and Windows. Can you guys please test it again?

**Comment by SteveRussell33** [comment]
Well done Alexey, that refactoring has done the job for me. Greater definition, certainly more accurate and able to better handle higher settings when pushed. Seems more "natural" and fluid and looks great in "lights off" dark mode, even when flicking through random settings.
I've got a folder of 5 presets that I'm happy with atm, will probably make some more. 
If you want to distribute the plugin with some, out of the box, "Factory" presets, let me know and I'll attach the folder so you can add them to the repo or I can do a PR for them at a later date. Dave will probably have some made up as well.

**Comment by davephillips** [comment]
Yep, that last work did the trick. Looking good here now. I don't know if I'll have any presets to add, but I am working on a demo, I'll let you know when it's ready for public view.

Thanks for the cool module, Alexey !

**Comment by alexey-komarov** [comment]
Thank you guys one more time again for being my beta testers :)
@SteveRussell33, yes, please share. I will add my own presets and release soon.

**Comment by alexey-komarov** [comment]
I have adjusted colors a bit, now saved presets can look differently, but they're kind of more controllable.
Also I've added some simple presets, so now presets can be added via pull request.

**Comment by alexey-komarov** [comment]
Looks like I can close this ticket. Thank you guys for you help and time once again.
BTW, I also added the Reset button, it was really missed there.
